### PR TITLE
Update sn_source_control.properties

### PR DESCRIPTION
**Pull request by ynassiri**

### CODE REVIEW

**Comment by ynassiri** [comment]
a

**Comment by ynassiri** [comment]
a

**Comment by jacebenson** [comment]
Hey

**Comment by ynassiri** [comment]
Hi, first thank you for sharing this app with public. 
By mistake i added comments here and i even tried to update one of the files (I thought i was working on my repo sorry).

**Comment by jacebenson** [comment]
no worries, glad you found it useful

**Pull request closed without merging**
